### ISSUE TITLE
Cannot find module 'eslint-plugin-react' 

### ISSUE THREAD

**Issue by alonalon** [sindresorhus/atom-linter-xo#19]
Hi, After last update I got following error when trying to lint.

```
Error: Failed to load plugin react: Cannot find module 'eslint-plugin-react'
Referenced from: 
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.module.exports.load (/Users/AronHafner/.dotfiles/atom.symlink/packages/linter-xo/node_modules/xo/node_modules/eslint/lib/config/plugins.js:116:26)
    at Array.forEach (native)
```

Have solved it with install `eslint-plugin-react` in the _packages/linter-xo/node_modules/xo_ path. But don't think thats a solution for the long term.

**Comment by Pszek** [comment]
+1

**Comment by artoale** [comment]
Same error, but installing `eslint-plugin-react` locally didn't fix the issue for me

**Comment by EloB** [comment]
Here is my workaround.

```bash
```

**Comment by kahlil** [comment]
I am using eslint-plugin-immutable and having the same problem. For some reason the linter does not find the plugins installed locally in the project. XO on the command line does not have the problem.

**Comment by kahlil** [comment]
Hm looking at the code @sindresorhus you are using `pkg-dir` to get the root of the project. Since the code of this Atom plugin `linter-xo` plugin is situated in `~/.atom/packages/linter-xo` could it be that `pkg-dir` does not work correctly, does not find the root of the project and in the end it will just use the default config from the Atom plugin itself?

**Comment by kahlil** [comment]
Nah this seems to work fine. Sorry.

**Comment by kahlil** [comment]
My last suspicion lies with the `.lintText()` function of the XO lib...

**Comment by mattbanks** [comment]
I'm having the same issue and posted about it in #10 with some more info on where this might be coming from and stack traces. @sindresorhus any thoughts on what might be happening here? I had to roll back to v0.13.0 to get things working again.

https://github.com/sindresorhus/atom-linter-xo/issues/10#issuecomment-194931376

https://github.com/sindresorhus/atom-linter-xo/issues/10#issuecomment-196892702

**Comment by wmertens** [comment]
Yeah, perhaps the chdir hack (removed in https://github.com/sindresorhus/atom-linter-xo/commit/a132bd8eaf08f87129444b4bc3e4614607162899#diff-168726dbe96b3ce427e7fedce31bb0bc) should stay in place - it doesn't really hurt to have it and it fixes plugin lookup it seems. (although the `chdir(dir)` should get a guard checking if dir is truthy)

**Comment by wmertens** [comment]
…err actually, since the hack was because eslint didn't have `cwd`, I thought maybe my eslint version was too old. However, after an "upgrade all the things" spree, the error still happens. The workaround remains installing the plugin in the linter-xo module dir under the atom packages

**Comment by sindresorhus** [comment]
This seems relevant: https://github.com/eslint/eslint/pull/5697 Can anyone try it out and see if it fixes things?

**Comment by kahlil** [comment]
> This seems relevant: eslint/eslint#5697 Can anyone try it out and see if it fixes things?

Updated eslint and it works! \o/

**Comment by mattbanks** [comment]
Updated global eslint, still seeing the issue. Should I update it inside `~/.atom/packages/linter-xo`?

**Comment by kahlil** [comment]
@mattbanks xo uses the local one if you have one installed. Do you have a local one as well?

**Comment by mattbanks** [comment]
Don't have a local copy specified in `package.json`, just `xo` (using npm2, so no flattened dependencies), but I went in there and run `npm update` to pull the latest eslint and that fixes everything for me too!

**Comment by kahlil** [comment]
@mattbanks your local xo installs a local version of eslint. Try deleting xo locally and reinstall.

**Comment by wmertens** [comment]
I don't have a global eslint, and both the local one as the one under linter-xo are 2.5.3, but the problem persists…

**Comment by mattbanks** [comment]
@kahlil blew away my local project `node_modules` folder and ran a fresh `npm install` and still having the issue. Also removed my global `eslint` and `xo` and reinstalled those as well (with an `npm cache clean`). Still getting the error in Atom.

**Comment by kahlil** [comment]
@mattbanks that sucks! So I am using an eslint plugin and an override in my setup and it seems to work fine after upgrading to the new eslint version...

**Comment by mattbanks** [comment]
I'm going to try adding eslint as a devDependency in this project and see if it works.

Here's my `package.json` (as much as I can post, since a lot of it is private modules):

```json
{
  "name": "my-project",
  "private": true,
  "version": "0.3.0",
  "description": "<redacted>",
  "author": "Matt Banks",
  "engines": {
    "node": "4.3.1"
  },
  "repository": {
    "type": "git",
    "url": "<redacted>"
  },
  "homepage": "<redacted>",
  "dependencies": {
    "bloxx": "~1.0.0",
    "body-parser": "~1.15.0",
    "cookie-parser": "~1.4.0",
    "dynamodb-engine": "~0.3.0",
    "enginemill": "~1.8.0",
    "express": "~4.13.0",
    "inflection": "~1.8.0",
    "jsonwebtoken": "~5.7.0",
    "nesh": "~1.6.0",
    "node-uuid": "~1.4.0",
    "password-hash-and-salt": "~0.1.0",
    "seneca": "~1.3.0",
    "y18n": "^3.2.0"
  },
  "devDependencies": {
    "babel-core": "~6.7.0",
    "babel-preset-es2015": "~6.6.0",
    "babel-preset-react": "~6.5.0",
    "babelify": "~7.2.0",
    "bluebird": "~3.3.0",
    "brixx": "~1.6.0",
    "browserify": "~13.0.0",
    "bunyan": "~1.7.0",
    "chai": "^3.5.0",
    "envify": "^3.4.0",
    "enzyme": "^2.2.0",
    "eslint-plugin-react": "^4.2.0",
    "gulp": "~3.9.0",
    "gulp-autoprefixer": "~3.1.0",
    "gulp-notify": "~2.2.0",
    "gulp-sass": "~2.2.0",
    "gulp-util": "~3.0.7",
    "immutable": "~3.7.0",
    "jasmine": "~2.4.0",
    "jsdom": "^8.2.0",
    "lodash": "~4.6.0",
    "minifyify": "~7.3.0",
    "mocha": "^2.4.5",
    "node-sass": "~3.4.0",
    "radium": "~0.16.6",
    "react": "~0.14.0",
    "react-addons-test-utils": "^0.14.7",
    "react-dnd": "^2.1.2",
    "react-dnd-html5-backend": "^2.1.2",
    "react-dom": "~0.14.0",
    "react-measure": "~0.3.4",
    "react-modal": "~0.6.1",
    "react-motion": "~0.4.2",
    "react-redux": "~4.4.0",
    "react-router": "~2.0.0",
    "react-select": "~1.0.0-beta9",
    "redux": "~3.3.1",
    "redux-devtools": "~3.1.0",
    "redux-devtools-dock-monitor": "~1.1.0",
    "redux-devtools-log-monitor": "~1.0.0-beta-3",
    "redux-form": "~4.2.0",
    "redux-logger": "~2.6.0",
    "redux-thunk": "~2.0.1",
    "vinyl-source-stream": "~1.1.0",
    "watchify": "~3.7.0",
    "whatwg-fetch": "^0.11.0",
    "xo": "~0.13.0",
    "yargs": "^4.2.0"
  },
  "xo": {
    "ignores": [
      "build/**",
      "public/**",
      "_builds/",
      "_cache/",
      "_steps/"
    ],
    "envs": [
      "node",
      "browser",
      "mocha"
    ],
    "globals": [
      "U",
      "html"
    ],
    "esnext": true,
    "plugins": [
      "react"
    ],
    "rules": {
      "react/jsx-uses-react": 2,
      "react/jsx-uses-vars": 2,
      "react/react-in-jsx-scope": 2
    }
  }
}
```

**Comment by sindresorhus** [comment]
New ESLint version is out. Can people experience problems try to reinstall `xo` (this will bring in latest ESLint) in their project and try again?

**Comment by mattbanks** [comment]
@sindresorhus I deleted the entire `node_modules` folder in 2 projects and reinstalled, and also removed both `eslint` and `xo` globally and reinstalled them. Still having the issue in Atom.

**Comment by sindresorhus** [comment]
I've added back the old cwd hack. Try reinstalling the plugin.

If it still doesn't work, it would be useful if anyone could share a repo where it's reproducible.

-

// @jamestalmage

**Comment by mattbanks** [comment]
Working for me after updating to v0.14.0 with the old cwd hack back in place! Thanks @sindresorhus 😃 ❤️

**Comment by Rowno** [comment]
After upgrading to Atom 1.12.0 I've started getting this error. Downgrading to Atom 1.11.1 fixes it.

**Comment by prattsj** [comment]
For anyone bumping into this and short on time to investigate like I am, I've worked around it for now by moving two packages:
```
eslint-config-xo-react
eslint-plugin-react
```
from `devDependencies` to `dependencies` in `~/.atom/packages/linter-xo/node_modules/xo/package.json`.

Then manually running:
```
$ apm i
```
from `~/.atom/packages/linter-xo`.

😕

**Comment by mhebrard** [comment]
Yesterday, I try to use xo on a react project.
I encounter the bug reported here.
use the method of @prattsj that fix the trouble
* manually change the xo dependencies
* amp i
* on my config I had to change the version of eslint in the dependencies list to avoid a UNMET PEER DEPENDENCY ERROR...

then that was working

today i saw the update from @sindresorhus 
I updated Atom with linter-xo v0.21.0
and get again 

Error: Failed to load plugin react: Cannot find module 'eslint-plugin-react

**Comment by marionebl** [comment]
Could you post the output of `npm ls eslint-plugin-react` @mhebrard ?

**Comment by mhebrard** [comment]
I had to play around all the version of my packages ... 
now, xo works well.

in `~/.atom/packages/linter-xo` I get
```
-- xo@0.17.1
  -- eslint-plugin-react@6.7.1
```

If it can help, in my specific project i have

```
"dependencies": {
[...]
    "eslint": "^3.6.0",
    "eslint-plugin-babel": "^3.2.0",
    "eslint-plugin-react": "^6.3.0",
[...]
  },
  "devDependencies": {
    "eslint-config-xo-react": "^0.10.0",
[...]
    "xo": "^0.17.0"
  },
  "xo": {
    "esnext": true,
    "extends": "xo-react",
    "space": 2,
    "envs": [
      "es6",
      "node",
      "browser"
    ]
  },
```

**Comment by jonathandelgado** [comment]
The bump to `0.21.0` resolves this for me, so I think there is some kind of irregularity in your environment.

Just spit-balling, could you try closing Atom and running `apm rm linter-xo` then `apm install linter-xo` and seeing if that works? I have had some flaky issues with APM updating in the past.

Additionally, make sure `xo` and your eslint things are installed in your project directory and not just listed in your `package.json`. `npm ls --depth=0` will do that for you.

**Comment by mhebrard** [comment]
I start from clean (I guess)
* uninstall atom
* remove `~/.atom`
* install atom
* in atom, install linter-xo v0.21.0
* use `xo --init --esnext`
* install eslint-config-xo-react `npm install --save-dev eslint-config-xo-react eslint-plugin-react`
* modify my eslint requirement version because of peer dependancy `"eslint": "^3.6.0"`
* add some config to xo (extends xo-react)
```
"xo": {
    "esnext": true,
    "space": 2,
    "envs": [
      "browser",
      "es6",
      "node"
    ],
    "extends": "xo-react"
  }
```
* delete `node_modules` folder and run clean `npm install`

at that point my react project is well linted...
* pure js linted
* JSX linted
* `import React from 'react';` do not cause problem...

good

but i get a bunch of `Error: Definition for rule 'react/[...] was not found`

So I feel the main issue is solved, thanks ...
an hint about the missing rules ?

**Comment by stevematdavies** [comment]
None of these suggestions fixes the issue. This error is the same with eslint as well as xo: I think this is a pretty serious eslint bug with Atom, and should be addressed immediately, it shouldn't still be an issue!!!! Using another editor until this is fixed.
